/* Main.c file generated by New Project wizard
 *
 * Created:   周6 5月08 2021  Aiho
 * Processor: ABOV A94B114
 * Compiler:  Keil C51
 */
 
/*            ------_____------
*         VSS|1              14| VDD     
*OTP      P10|2              13| P00   GEAR0
*GEAR6    P11|3              12| P01	 GEAR1
*ZERO     P12|4              11| P02 	 GEAR2			
*LED      P13|5              10| P03	 GEAR3
*HALL 	  P14|6               9| P04	 GEARP     
*OUT_TR   P15|7               8| P05	 GEAR4 
*OUT_DLY  P07|7               8| P06	 GEAR5 
*              -----------------
*			               A94B114
*/

#include "Main.h"

/*const uint8_t  MotoCounts_75[] =   //75:1 13齿
{
    0,
    CALC_COUNTS(3000),     // [] counts 40    1   
    CALC_COUNTS(4500),     // [] counts 60    2   
    CALC_COUNTS(6000),     // [] counts 80    3   
    CALC_COUNTS(8300),     // [] counts 110   4  
    CALC_COUNTS(12000),    // [] counts 160   5 
    CALC_COUNTS(15800),    // [] counts 210   6 
    CALC_COUNTS(15800)     // [] counts 210   P  
}; */

const uint8_t  MotoCounts_65[] =  //65:1 15齿
{
    0,
    CALC_COUNTS(2600),     // [] counts 40    1   
    CALC_COUNTS(3900),     // [] counts 60    2   
    CALC_COUNTS(5200),     // [] counts 80    3   
    CALC_COUNTS(7200),     // [] counts 110   4  
    CALC_COUNTS(10400),    // [] counts 160   5 
    CALC_COUNTS(13700),    // [] counts 210   6 
    CALC_COUNTS(13700)     // [] counts 210   P  
};


const uint8_t  MotoCounts_51[] = //51:1 19齿
{
    0,
    CALC_COUNTS(2100),  // [] counts on 100ms     1
    CALC_COUNTS(3100),  // [] counts on 100ms     2
    CALC_COUNTS(4100),  // [] counts on 100ms     3
    CALC_COUNTS(5600),  // [] counts on 100ms     4
    CALC_COUNTS(8200),  // [] counts on 100ms     5
    CALC_COUNTS(10800), // [] counts on 100ms     6
    CALC_COUNTS(10800)  // [] counts on 100ms     P
};
//[15/19Cnt]
const uint8_t CurOverMax[2][2][3] = //[50/60Hz][65/51Cnt][G0/G1/G3]
{
//    {{110,90,70} /*60Hz/51Cnt*/,	{100,80,60}/*60Hz/75Cnt*/},
//    {{120,100,80}/*50Hz/51Cnt*/,	{110,90,70}/*50Hz/75Cnt*/}
    
    {{90,78,55} /*60Hz/51Cnt*/,	{90,70,40}/*60Hz/75Cnt*/},			//67--72--78		37--42--55
    {{115,102,72}/*50Hz/51Cnt*/,	{110,95,60}/*50Hz/75Cnt*/}		//90--95		//87--97--102		57-67--72	
};

const uint8_t Gear_Mask[] = {0x01,0x02,0x04,0x08,0x20,0x40,0x80,0x10};


typedef struct _pid
{
	uint8_t Proportion;
	uint8_t Integral;
	uint8_t Derivative;
	uint8_t NextPoint;
	uint8_t SetPoint;
	uint8_t NextPointLast;
	const uint8_t* MotoCounts; 
	int IncPID_Val;
	int Error;
	int Error1;
	int Error2;
}Pid_t;
	
Pid_t Pid;

uint16_t ErrCnts = 0;

//±?λ1
volatile bit MotoRunFlag;

//±?λ2
volatile bit AcTestFlag;
volatile bit Ac50HzFlag;
volatile bit GearRatioFlag;
volatile bit HeatSwFlag;
volatile bit ZeroLastFlag;
volatile bit ReturnZero;

//±?λ3
volatile bit HallValLast;
uint8_t HallCnt;

uint8_t SetPointFlag;
uint8_t HallCount;

uint8_t KeyCnt;


//LED±?λ
uint8_t LedMode;
uint8_t LedFlashCnt;

//??±?λ

uint8_t TimeCnt;

uint8_t  AcCnt;
uint16_t AcTestTime;

uint16_t ZeroCnt;
uint8_t MotoGear;

uint8_t DelaySetCnt;


uint8_t  OverUpCnt;
uint8_t  OverDownCnt;

uint8_t TriacState;
uint8_t TriacOutCnt;

uint8_t Limit_min;
int TriacDuty;

volatile bit bit_sdfastchk;

void GetAcPeriod(void);
void Key_Task(void);
void Led_Task(void);
void Moto_Task(void);
void PidInit(void);
void HallScan(void);
void GetOption(void);
void GetMotoOver(void);

void Err_Task(void)
{
    ;
}

void Dev_Tick_Reload(uint8_t tick)  //?????o40uS
{
	T0DR = tick;
}

void Dev_Tick_Set(void)
{    
	Dev_Tick_Reload(TICK); 
	T0CR = 0x85;    //????? FOSC/8 ;: 2·?μ    
}

void Dev_Dog_Set(void)
{
	WDTR = 0xFF;
	WDTMR = 0x3F;
}

void Dev_Dog_Food(void)
{
    WDTMR |= 0x04;
}

void Dev_Io_Set(void)
{
	P0 = 0x7F;
	P0IO = 0x80;
	P0PU = 0x7F;
	P0OD = 0x00;
	P0DB = 0x7F;
	P1 = 0x3F;
	P1IO = 0xE8;
	P1PU = 0x07;
	P1OD = 0x00;
	P1DB = 0x27;
	P2 = 0x00;
	P2IO = 0x00;
	P2PU = 0x00;
	P2OD= 0x00;
	P2DB = 0x00;
}



void Usr_Init(void)
{
	SET_LED(LED_FLASH);
	OS_Task_Init();
	OS_Request_Task(TaskLed);	
}

void WaitUs( unsigned char a_unTime )
{
	unsigned char	i;

	for(i = 0; i < a_unTime; i ++)
	{
		;
	}
}

unsigned char sdkeychk(void)
{
	unsigned char keychk;
	
	keychk =0xff;
	WaitUs(100);
	keychk = P0&0x7f;
	keychk  |= GEAR6?0x80:0x00;
	if(keychk!=0xfe)
		return(0);
		
	keychk =0xff;
	WaitUs(100);
	keychk = P0&0x7f;
	keychk  |= GEAR6?0x80:0x00;
	if(keychk!=0xfe)
		return(0);
		
	keychk =0xff;
	WaitUs(100);
	keychk = P0&0x7f;
	keychk  |= GEAR6?0x80:0x00;
	if(keychk!=0xfe)
		return(0);
		
	keychk =0xff;
	WaitUs(100);
	keychk = P0&0x7f;
	keychk  |= GEAR6?0x80:0x00;
	if(keychk!=0xfe)
		return(0);
		
	bit_sdfastchk =1;
	ReturnZero = 1; 
	SET_LED (LED_FLASH);
	SET_SCR_OFF(MotoRunFlag);
	return(1);
}

void Mcu_Init(void)
{
	di();
	SYSCON_AR = 0x5A;  //设置时钟 ＝ 16Mhz
	SCCR = 0x40;
	OSCCR = 0x04;
	SYSCON_AR = 0x5A;
	Dev_Io_Set();
	Dev_Tick_Set();
	Dev_Dog_Set();
	IE1 = 0x10; 
	IE2 = 0x08; 
	ei();
	Usr_Init();
	
	sdkeychk();
}

void main(void)
{
	uint8_t i;
	
	Mcu_Init();
	GetOption();
	LVIR  = 0x03;			//	
	
	while(1)
	{
		i = 0;
		while (i <= task_number)
		{
			Dev_Dog_Food();
			if ((TCB[2*i] & 0xf0) ==  0x80)			//Ready bit check
			{
				Current_Task = i;					//Ready then dispatch to task
				switch (i)
				{
					OS_Dispatch(TaskMoto, Moto_Task()); 
					OS_Dispatch(TaskKey, Key_Task());
					OS_Dispatch(TaskLed, Led_Task());
					default:
					{
						Err_Task();
						break;
					}
				}
				i = 1;								//Round Robin then first task
			}
			else
			i++;								//got to next task
		}
	}
}


//中断
void TimeTick(void) interrupt 9   
{
	GetAcPeriod();
	HallScan();
	if(++TimeCnt>=25)
	{
		TimeCnt = 0;
		OS_Timer_Update();    //1ms
	} 
}

//中断
void LowVolDefault(void) interrupt 15   
{
	SET_SCR_OFF(MotoRunFlag);
	SET_LED(LED_FLASH);
}

void Delay_Ms(uint8_t Cnt)
{
    uint16_t i;

    for (; Cnt > 0 ; --Cnt)
    {
        for (i = 1000; i > 0; --i)
            Dev_Dog_Food();
    }
}



//获取交流输入电网周期
void GetAcPeriod(void)
{
	switch(TriacState)
	{
		case 1:
			if(++TriacOutCnt < TriacDuty)
				break;
			TriacState ++;
			TriacOutCnt = 0;
			Moto_Pwm = 0;
			break;
		case 2:
			if(++TriacOutCnt < PULSE_MIN)
				break;
			TriacState = 0;
			TriacOutCnt = 0;
			Moto_Pwm = 1; 
			break;
		default:
			TriacState = 0;
			Moto_Pwm = 1; 
			TriacOutCnt = 0;
			break;
	}
	if((Zero == ZeroLastFlag) && (ZeroCnt < ZERO_CNT_LIMIT))
	{
		ZeroCnt++;
		return;
	}
	ZeroLastFlag = Zero;
	if(MotoRunFlag)
	{
		TriacState = 1;
		TriacOutCnt = 0;
		Moto_Pwm = 1; 
	}
	if((ZeroCnt<ZERO_CNT_MIN) || (ZeroCnt>ZERO_CNT_MAX))
	{
		ZeroCnt = 0;
		return;
	}
	
	AcTestTime += ZeroCnt;
	ZeroCnt = 0;
	if (AcCnt < 15)					//15
	{
		AcCnt++;
		return;
	}
	AcCnt = 0;
	AcTestTime >>=4;   //50Hz:2500; 60Hz:2000			//4
	if(AcTestTime>ZERO_CNT_50HZ)
	{
		Ac50HzFlag = 1;
		Limit_min = AC_50Hz-PULSE_MIN-LIMIT_MIN;
		Pid.Proportion = Kp_50Hz; // PID Kp
		Pid.Integral = Ki_50Hz;   // PID Ki
		Pid.Derivative = Kd_50Hz; // PID Kd
	}
	else
	{
		Ac50HzFlag = 0;
		Limit_min = AC_60Hz-PULSE_MIN-LIMIT_MIN;
		Pid.Proportion = Kp_60Hz; // PID Kp
		Pid.Integral = Ki_60Hz;   // PID Ki
		Pid.Derivative = Kd_60Hz; // PID Kd		
	}
	AcTestTime = 0;
	if(AcTestFlag)
		return;
	AcTestFlag = 1;
	OS_Trigger_Task(TaskKey);
}


void GetOption(void)
{
	uint8_t TmpOpt;

	TmpOpt = OTP1? 0x01:0x00;
	Delay_Ms(5);
  	if(TmpOpt != (OTP1? 0x01:0x00))
		TmpOpt = 0x01;
	if(TmpOpt)
	{
		GearRatioFlag = 1;
		Pid.MotoCounts = MotoCounts_65;
	}
	else
	{
		GearRatioFlag = 0;
		Pid.MotoCounts = MotoCounts_51;
	}
}



void HallScan(void)
{
	uint8_t HallVal;
    
	HallVal = HALL;
	if(HallVal != HallValLast)
  {
    HallValLast = HallVal;
    HallCnt = 0;
	}
	else
	{
		if(HallCnt > 1)
			return;
		if(++HallCnt == 1 )
			HallCount++;
	}
}

//???绺·′à???y?3劽
uint8_t Get_MotoCount(void)
{
	uint8_t Count;
   
	Count = HallCount;
	HallCount = 0;
	return Count;
}

//μ绺PID3???
void PidInit(void)
{
    // state variables
	Pid.Error = 0;
	Pid.Error1 = 0;
	Pid.Error2 = 0;
	OverDownCnt = 0;
	OverUpCnt = 0;
	TriacDuty = Limit_min;
	Get_MotoCount();
	ErrCnts = 0;
}

//μ绺PID???
void Moto_Task(void)
{
	int TempDuty;
	
	if(MotoRunFlag == 0)
	{
		OS_Exit_Task();
		return;
	}
	OS_Wait_Timer(25);
	Pid.NextPoint = (uint8_t)Get_MotoCount();
	if((Pid.NextPoint < 1) || (Pid.NextPoint > (Pid.MotoCounts[GEAR_P]+20)))   //?˙1yμ????
	{
	  if(++ErrCnts > 200)
	  {
			ErrCnts = 0; 
			SET_SCR_OFF(MotoRunFlag);
			SET_LED(LED_FLASH);
	  }
	} 
	else
	  ErrCnts = 0; 
	Pid.Error = (int)Pid.SetPoint - (int)Pid.NextPoint;            // do PID
	Pid.IncPID_Val = (int)Pid.Proportion *(Pid.Error- Pid.Error1)                   // P
							+(int)Pid.Integral * Pid.Error*10/10                                    // I
							+(int)Pid.Derivative * (Pid.Error-2*Pid.Error1+Pid.Error2);              // D
	if(Pid.IncPID_Val < -ERR_MAX) Pid.IncPID_Val = -ERR_MAX;
	Pid.Error2=Pid.Error1;                          
	Pid.Error1=Pid.Error;
	TempDuty = TriacDuty;
	TempDuty -= Pid.IncPID_Val;
	if(TempDuty <  LIMIT_MAX)
		TempDuty =  LIMIT_MAX;
	else if(TempDuty >  Limit_min)
		TempDuty =   Limit_min;
	di();
	TriacDuty = TempDuty;
	ei();
	GetMotoOver();
	if(SetPointFlag)
		return;
	if(Pid.SetPoint > Pid.MotoCounts[MotoGear])
	{
			Pid.SetPoint--; 
			DelaySetCnt = 0;
	}
	else if(Pid.SetPoint < Pid.MotoCounts[MotoGear])
	{
		if(DelaySetCnt++ >1)
		{
			if(MotoGear==GEAR_P)
			{
				Pid.SetPoint +=3;
			}
			else
			{
				Pid.SetPoint++;
			}
			DelaySetCnt = 0;
		}
	}
	else
	{
		SetPointFlag = 1;
		DelaySetCnt = 0;
	}
}

void GetMotoOver(void)
{
	if(MotoGear > GEAR_3)
		return;
	if(TriacDuty < CurOverMax[Ac50HzFlag][GearRatioFlag][MotoGear-1])
	{
		OverDownCnt = 0;
		if(++OverUpCnt < MOTO_CUR_HIG_CNT)
			return;
		OverUpCnt = 0;
		SET_SCR_OFF(MotoRunFlag);
		SET_LED(LED_FLASH);
	}
	else
	{
		if(++OverDownCnt <  MOTO_CUR_LOW_CNT)
			return;
		OverDownCnt = 0;
		OverUpCnt = 0;
	}
}


void Key_Task(void)
{
	uint8_t i,KeyVal;
	uint8_t Key = 0xff;

	if(!bit_sdfastchk)
	{
//		OS_Wait_Timer(1); 		//5--5ms		
	}
	else
	{
		OS_Wait_Timer(20); 		 //20ms
	}
	
	KeyVal = P0&0x7f;
	KeyVal  |= GEAR6?0x80:0x00;
	for(i = 0; i<GEAR_N; i++)
	{
		if((KeyVal&Gear_Mask[i]) == 0)
		{
			Key = i;
			break;
		}
	}
	if(Key > 0x80)
		return;
	if(Key != MotoGear)
	{
		KeyCnt = 0;
		MotoGear = Key;
	}
	else
	{
		if((KeyCnt > KEY_PRESS)&&(bit_sdfastchk))
//		if(KeyCnt > KEY_PRESS)
			return;    
		if ((KeyCnt++ == KEY_PRESS)||(!bit_sdfastchk))
//		if (KeyCnt++ == KEY_PRESS)
		{
			if(MotoGear == 0)
			{
				bit_sdfastchk =1;
				ReturnZero = 1; 
				SET_LED (LED_FLASH);
				SET_SCR_OFF(MotoRunFlag);
				return;
			}
			else
			{
				SetPointFlag = 0;
				OverDownCnt = 0;
				OverUpCnt = 0;
				if(ReturnZero)
				{ 
					if(MotoGear == GEAR_P)
						Pid.SetPoint = 5;		//10	
					else
						Pid.SetPoint = 2;			//2	
					PidInit();
					SET_SCR_ON(MotoRunFlag);
					OS_Request_Task(TaskMoto);
					SET_LED(LED_ON);
					ReturnZero = 0;
				}
				else if(MotoRunFlag == 0)
					SET_LED(LED_FLASH);
			}
		}
	}
}

//设置档位灯
void Led_Task(void)
{
	OS_Wait_Timer(10);  //10ms
	switch(LedMode)
	{
		case LED_ON:
		case LED_OFF:
			Led_Pwm = LedMode?1:0;
			LedFlashCnt = 0;
			LedMode = 0xff;
			break;
		case LED_FLASH:
			if(LedFlashCnt)
				LedFlashCnt--;
			else
			{
				Led_Pwm = ~Led_Pwm;
				LedFlashCnt =LED_FLASH_CNT;
			}
			break;
	}
}






	